[package]
name = "aoc2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoize = "0.4.2"
rayon = "1.8.0"
strum = {version="0.25.0", features=["derive"]}
